esphome:
  name: "espfan"
  friendly_name: "espfan"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1wNUQinIHn/IhqY8RswZVcU9Yw4G+Gx1BVdlhKZgP34="

ota:
  - platform: esphome
    password: "57541e756299f6918a7d5b86bb8cef05"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Fallback Hotspot"
    password: "l0N2nzcLMHbf"

captive_portal:

output:
  - platform: ledc
    pin: GPIO25
    frequency: 25000 Hz
    id: fan_pwm

fan:
  - platform: speed
    output: fan_pwm
    name: "PC Fan"
    id: pc_fan
    speed_count: 100
    
sensor:
  - platform: adc
    pin: GPIO34
    name: "Fan Pot"
    id: fan_pot
    update_interval: 100ms
    attenuation: 12db   # Allows reading up to ~3.9V
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      # NEW MAPPING: 0V is 0%, 3.3V is 100%
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 100.0
      # Only update if value changes by 1%
      - delta: 1.0
    unit_of_measurement: "%"
    on_value:
      then:
        - fan.turn_on:
            id: pc_fan
            speed: !lambda "return x;"

  - platform: pulse_counter
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    name: "Fan RPM"
    id: fan_rpm
    update_interval: 2s
    unit_of_measurement: "RPM"
    filters:
      # FIX 3: Correct Math (pulses/min / 2 pulses/rev = RPM)
      - multiply: 0.5

# FIX 4: The 'interval' block is deleted because 'on_value' above handles it now.
